### ISSUE TITLE
大佬，有没有考虑过把hiprint运行到node后端

### ISSUE THREAD

**Issue by littlechencn** [Xavier9896/node-hiprint-transit#1]
大佬，有没有考虑过把hiprint运行到node后端，在node里使用模拟的window对象，最终以http接口形式提供服务。

**Comment by Xavier9896** [comment]
我尝试过了，使用 jsdom 创建 window、document 对象，不过仍有很多问题(canvas、localStorage)，暂时停止研究了。
![image](https://github.com/Xavier9896/node-hiprint-transit/assets/34981520/120d68d2-55ee-412b-ba7d-2db994a81c96)

**Comment by Xavier9896** [comment]
喜大普奔，初步研究出来了
![image](https://github.com/Xavier9896/node-hiprint-transit/assets/34981520/2f1e0a1a-715b-4c95-bf92-7e3c5e389b0f)
![image](https://github.com/Xavier9896/node-hiprint-transit/assets/34981520/dd5abf3f-ff0f-4419-ae75-c2f199c09ae8)

**Comment by Xavier9896** [comment]
失败了，jsdom毕竟是虚拟的节点，并没有真实渲染，table、longText 自动分页依赖的 offsetHeight 获取不到，导致分不了页，只能实现到下面这个效果为止。vue-plugin-hiprint 里面有挺多都需要依赖 offsetHeight 的功能，所以 jsdom 这个方向应该是进行不下去的了。https://github.com/jsdom/jsdom/issues/135
![image](https://github.com/Xavier9896/node-hiprint-transit/assets/34981520/3401ba83-7b2f-4df2-99cc-3afcc0530e7e)
