### ISSUE TITLE
使用vue-plugin-hiprint通过中转打印，获取不到打印机列表，直接连客户端就可以获取

### ISSUE THREAD

**Issue by HowardNiu** [Xavier9896/node-hiprint-transit#2]
![11111111](https://github.com/Xavier9896/node-hiprint-transit/assets/101862180/c169cdae-9030-4545-a8fa-78d23d91e6c7)
![22222222](https://github.com/Xavier9896/node-hiprint-transit/assets/101862180/2351c3a8-42dd-42c8-b84c-a0658b5c234f)
请大佬看看我贴的这两张图，分别是通过中转连接和直接连接客户端，请忽略setTimeout（这是因为我没找到怎么写callback），不报错，通过中转就是获取的打印机列表为空，换成连客户端就行，下面是打印结果
![33333333](https://github.com/Xavier9896/node-hiprint-transit/assets/101862180/c9c706d8-7ced-44af-9da9-657e7cb94e12)
再贴一张我的中转服务和客户端服务，均运行在本地
![44444444](https://github.com/Xavier9896/node-hiprint-transit/assets/101862180/c38797ca-cf27-472c-a729-a585e9232dd9)
vue-plugin-hiprint是拉的您的start的那个Demo，直接用客户端也可以正常打印
烦请指导！

**Comment by Xavier9896** [comment]
setHost 需要传入 token，你连接中转没有传 token，init 与 setHost 只需要写一个，init 传入了 host 与 token 就不用重新 setHost

**Comment by HowardNiu** [comment]
> setHost 需要传入 token，你连接中转没有传 token，init 与 setHost 只需要写一个，init 传入了 host 与 token 就不用重新 setHost
传token会报错e is not function，谢谢大佬回复，麻烦再看一下
![issue](https://github.com/Xavier9896/node-hiprint-transit/assets/101862180/d2029831-6a13-4a37-9a13-c35a3cda8097)
这是我修改后的代码
![55555555](https://github.com/Xavier9896/node-hiprint-transit/assets/101862180/83e480fb-bb15-4bd4-9c24-954430b7c7f0)

**Comment by Xavier9896** [comment]
你用的 vue-plugin-hiprint 版本太低，不支持 token，所有不支持中转发自我的 iPhone在 2024年6月4日，20:02，oaNq ***@***.***> 写道：﻿

setHost 需要传入 token，你连接中转没有传 token，init 与 setHost 只需要写一个，init 传入了 host 与 token 就不用重新 setHost
传token会报错e is not function，谢谢大佬回复，麻烦再看一下
issue.jpg (view on web)
这是我修改后的代码
55555555.jpg (view on web)

**Comment by HowardNiu** [comment]
我用的是官方的start的Demo：https://github.com/CcSimple/vue-plugin-hiprint-start
烦请更新一下这个Demo依赖的版本吧，作为初学者确实感觉频繁受阻。。

**Comment by HowardNiu** [comment]
用setHost的回调，不稳定呢，只能偶尔获取到打印机列表

**Comment by HowardNiu** [comment]
可否给个用vue-plugin-hiprint连接中转能打印的demo？我这试着怎么都不行呢。。
![66666666](https://github.com/Xavier9896/node-hiprint-transit/assets/101862180/1e21a8a3-6624-4aa9-bbcc-c9314baf4d70)
![77777777](https://github.com/Xavier9896/node-hiprint-transit/assets/101862180/4b64d628-6c9e-47ad-bdf5-68eef6ff9b3d)

**Comment by Xavier9896** [comment]
getPrinterList() 接口是异步的，并且没有返回异步，需要你自己用 hinnn.event.on("printerList", (arr) => {}) 捕获异步返回

**Comment by Xavier9896** [comment]
从截图来看你的业务逻辑不太对，应该在组件 created、mounted 生命周期去 init，然后让用户自行选择 打印机，再调用 print2

如果使用默认打印机，不应该 从 printList[0] 去获取打印机，应该缺省 printer，程序会默认使用默认打印机
